### ISSUE TITLE
This action doesn't work in Windows

### ISSUE THREAD

**Issue by Ana06** [stefanbuck/github-issue-parser#22]
I have realised that this action doesn't work in windows. I get the following error:
```
(node:6056) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'undefined/issue-parser-result.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at run (D:\a\_actions\stefanbuck\github-issue-parser\v2\dist\index.js:121:6)
    at Object.932 (D:\a\_actions\stefanbuck\github-issue-parser\v2\dist\index.js:135:3)
    at __nccwpck_require__ (D:\a\_actions\stefanbuck\github-issue-parser\v2\dist\index.js:4803:43)
    at D:\a\_actions\stefanbuck\github-issue-parser\v2\dist\index.js:4821:37
    at Object.<anonymous> (D:\a\_actions\stefanbuck\github-issue-parser\v2\dist\index.js:4824:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
(node:6056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I _think_ it is because `env.HOME` is not defined in Windows.

**Comment by stefanbuck** [comment]
Thanks for letting me know. This has been fixed in [2.0.1](https://github.com/stefanbuck/github-issue-parser/releases/tag/v2.0.1).
